name: pymathics-asy (windows)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-lastest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # sudo apt-get update -qq && sudo apt-get install -qq liblapack-dev llvm-dev
        # sudo apt-get install -qq asymptote
        python -m pip install --upgrade pip
        python -m pip install -e git://github.com/mathics/Mathics.git#egg=Mathics3
    - name: Install Package
      run: |
        make develop
    - name: Test Package
      run: |
        pip install pytest pexpect
        export DISPLAY=""
        python test/tmp_exporters.py 
        make -j3 check
